# codecov.yml file, spec is visible:
# https://github.com/codecov/support/wiki/Codecov-Yaml
coverage:
  status:
    project:
      default: false
      tests:
        paths:
          - "tests/"
        target: auto
    patch:
      default:
        target: 5%
