[tool.poetry]
name = "openapi2callables"
homepage = "https://github.com/andrewbolster/openapi2callables"
version = "0.1.0"
description = "Experiment in parsing and projecting OpenAPI endpoints into OpenAI/GenericLLM compatible Tools (but should also be generic enough for non-llm directed usage...)"
authors = ["Andrew Bolster <andrew@bolster.online>"]
readme = "README.md"
packages = [{include = "openapi2callables"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.0"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
openapi2callables = "openapi2callables.cli:cli"
