name: Rebase pull requests
permissions:                    # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests
on:
    push:
    release:
        types: [published]
jobs:
    auto-rebase:
        name: rebase dependabot PRs
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' || github.event == 'release'
        timeout-minutes: 5
        steps:
            - name: rebase
              uses: "bbeesley/gha-auto-dependabot-rebase@main"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
