name: Bump version and push tag

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run tests
        run: uv run pytest tests --cov-branch --cov-report=xml --cov=openapi2callables --cov --junitxml=junit.xml -o junit_family=legacy

      - name: Check code coverage
        run: uv run coverage report --fail-under=80

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: patch
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

      - name: Push changes
        run: |
          git push origin main --tags